#spring:
#  application:
#    name: aws-spring
#  data:
#    mongodb:
#      uri: mongodb://${MONGODB_USER}:${MONGODB_PWD}@${MONGODB_HOST:localhost:21017}?authSource=admin&readPreference=primary&ssl=false
#      database: ${MONGODB_NAME:aws-spring}

#spring:
#  datasource:
#    url: jdbc:mysql://${SQL_HOST:localhost:3306}/${SQL_DB:spring}
#    username: ${SQL_USER:root}
#    password: ${SQL_PASS:root}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect